allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  es5-ext: false
  esbuild: false
  protobufjs: false
  sharp: false
minimumReleaseAgeExclude:
  - '@univerjs/*'
  - '@univerjs-pro/*'
  - '@amamo/*'
  - '@next/*'
  - next
patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
