import documents from '@/.amamo-mdx/guides-navigation.json'

import { createAmamoMetadataSource, type IAmamoMetadata } from '../amamo-metadata'
import { createGuidesLoader } from './loader'

// Generated by the same validated collection build as the article registry.
// A JSON import remains watched by Next without adding MDX load() imports to menu pages.

export const guideNavigationSource = createGuidesLoader(
  await createAmamoMetadataSource(
    'guides',
    'content/guides',
    documents as IAmamoMetadata<{ title: string; description?: string; icon?: string }>[],
  ),
)
