export default {
  'general-api': 'Basic API',
  'sheet-api': 'Sheet API',
  'permission': 'Permission',
  'formula': 'Formula',
  'numfmt': 'Number Format',
  'row-col': 'Row & Column',
  'range-selection': 'Range & Selection & Cell',
  'freeze': 'Freeze',
  'clipboard': 'Clipboard',
  'dom': 'Custom Component',
  'default-style': 'Default Style',
  'gridlines': 'Gridlines',
  'range-theme': 'Range Theme',
  'rich-text': 'Rich Text',
  'worker': 'Worker',
  'defined-names': 'Defined Names',
}
