import type { ISlideData } from '@univerjs-pro/slides'
import { ShapeTypeEnum } from '@univerjs-pro/engine-shape'
import { PageElementTypeEnum, PageTypeEnum, SlideBackgroundTypeEnum } from '@univerjs-pro/slides'
import { LocaleType } from '@univerjs/core'

export const homeSlideData: ISlideData = {
  id: 'launch-story-slides',
  name: 'Q3 Product Launch',
  appVersion: '1.0.0-beta.1',
  rev: 1,
  locale: LocaleType.EN_US,
  defaultPageSize: {
    width: 1200,
    height: 675,
  },
  slideOrder: ['cover', 'signals', 'roadmap', 'close'],
  activeSlideId: 'cover',
  slides: {
    cover: {
      id: 'cover',
      pageType: PageTypeEnum.Slide,
      name: 'Cover',
      background: {
        type: SlideBackgroundTypeEnum.Solid,
        color: '#081423',
      },
      elementOrder: ['glow', 'eyebrow', 'title', 'subtitle', 'metric-card', 'metric-value', 'metric-label', 'footer'],
      elements: {
        glow: {
          id: 'glow',
          type: PageElementTypeEnum.Shape,
          transform: {
            left: 784,
            top: -110,
            width: 530,
            height: 530,
            rotation: 0,
          },
          shapeData: {
            shapeType: ShapeTypeEnum.Ellipse,
            fill: { color: '#1F9BFF' },
            stroke: { color: '#1F9BFF', width: 0 },
          },
        },
        eyebrow: {
          id: 'eyebrow',
          type: PageElementTypeEnum.Text,
          transform: {
            left: 92,
            top: 92,
            width: 430,
            height: 36,
            rotation: 0,
          },
          text: 'Q3 PRODUCT LAUNCH  /  EXECUTIVE BRIEF',
          textStyle: {
            color: '#7DD3FC',
            fontSize: 16,
            bold: true,
          },
        },
        title: {
          id: 'title',
          type: PageElementTypeEnum.Text,
          transform: {
            left: 88,
            top: 162,
            width: 720,
            height: 170,
            rotation: 0,
          },
          text: 'Workflows that move\nwith your team',
          textStyle: {
            color: '#F8FAFC',
            fontSize: 54,
            bold: true,
          },
        },
        subtitle: {
          id: 'subtitle',
          type: PageElementTypeEnum.Text,
          transform: {
            left: 92,
            top: 366,
            width: 620,
            height: 84,
            rotation: 0,
          },
          text: 'A connected launch system spanning planning, content, data, and delivery.',
          textStyle: {
            color: '#A8B6C8',
            fontSize: 22,
          },
        },
        'metric-card': {
          id: 'metric-card',
          type: PageElementTypeEnum.Shape,
          transform: {
            left: 842,
            top: 328,
            width: 264,
            height: 190,
            rotation: 0,
          },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#F8FAFC' },
            stroke: { color: '#DBEAFE', width: 1 },
          },
        },
        'metric-value': {
          id: 'metric-value',
          type: PageElementTypeEnum.Text,
          transform: {
            left: 882,
            top: 370,
            width: 190,
            height: 70,
            rotation: 0,
          },
          text: '82%',
          textStyle: {
            color: '#0F172A',
            fontSize: 48,
            bold: true,
          },
        },
        'metric-label': {
          id: 'metric-label',
          type: PageElementTypeEnum.Text,
          transform: {
            left: 884,
            top: 450,
            width: 180,
            height: 40,
            rotation: 0,
          },
          text: 'LAUNCH READY',
          textStyle: {
            color: '#0284C7',
            fontSize: 16,
            bold: true,
          },
        },
        footer: {
          id: 'footer',
          type: PageElementTypeEnum.Text,
          transform: {
            left: 92,
            top: 590,
            width: 780,
            height: 30,
            rotation: 0,
          },
          text: 'UNIVER  ·  ONE SDK, EVERY WORKSPACE',
          textStyle: {
            color: '#64748B',
            fontSize: 14,
            bold: true,
          },
        },
      },
    },
    signals: {
      id: 'signals',
      pageType: PageTypeEnum.Slide,
      name: 'Signals',
      background: {
        type: SlideBackgroundTypeEnum.Solid,
        color: '#F8FAFC',
      },
      elementOrder: [
        'title',
        'subtitle',
        'bar-1',
        'bar-2',
        'bar-3',
        'label-1',
        'label-2',
        'label-3',
        'value-1',
        'value-2',
        'value-3',
      ],
      elements: {
        title: {
          id: 'title',
          type: PageElementTypeEnum.Text,
          transform: { left: 86, top: 70, width: 800, height: 64, rotation: 0 },
          text: 'Signals are moving in the right direction',
          textStyle: { color: '#0F172A', fontSize: 36, bold: true },
        },
        subtitle: {
          id: 'subtitle',
          type: PageElementTypeEnum.Text,
          transform: { left: 88, top: 142, width: 740, height: 42, rotation: 0 },
          text: 'Week-over-week progress against launch targets',
          textStyle: { color: '#64748B', fontSize: 19 },
        },
        'bar-1': {
          id: 'bar-1',
          type: PageElementTypeEnum.Shape,
          transform: { left: 88, top: 250, width: 840, height: 58, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#0EA5E9' },
            stroke: { color: '#0EA5E9', width: 0 },
          },
        },
        'bar-2': {
          id: 'bar-2',
          type: PageElementTypeEnum.Shape,
          transform: { left: 88, top: 382, width: 704, height: 58, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#22C55E' },
            stroke: { color: '#22C55E', width: 0 },
          },
        },
        'bar-3': {
          id: 'bar-3',
          type: PageElementTypeEnum.Shape,
          transform: { left: 88, top: 514, width: 594, height: 58, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#F59E0B' },
            stroke: { color: '#F59E0B', width: 0 },
          },
        },
        'label-1': {
          id: 'label-1',
          type: PageElementTypeEnum.Text,
          transform: { left: 90, top: 212, width: 320, height: 30, rotation: 0 },
          text: 'Product readiness',
          textStyle: { color: '#334155', fontSize: 17, bold: true },
        },
        'label-2': {
          id: 'label-2',
          type: PageElementTypeEnum.Text,
          transform: { left: 90, top: 344, width: 320, height: 30, rotation: 0 },
          text: 'Content coverage',
          textStyle: { color: '#334155', fontSize: 17, bold: true },
        },
        'label-3': {
          id: 'label-3',
          type: PageElementTypeEnum.Text,
          transform: { left: 90, top: 476, width: 320, height: 30, rotation: 0 },
          text: 'Regional enablement',
          textStyle: { color: '#334155', fontSize: 17, bold: true },
        },
        'value-1': {
          id: 'value-1',
          type: PageElementTypeEnum.Text,
          transform: { left: 966, top: 258, width: 120, height: 44, rotation: 0 },
          text: '82%',
          textStyle: { color: '#0F172A', fontSize: 28, bold: true },
        },
        'value-2': {
          id: 'value-2',
          type: PageElementTypeEnum.Text,
          transform: { left: 966, top: 390, width: 120, height: 44, rotation: 0 },
          text: '68%',
          textStyle: { color: '#0F172A', fontSize: 28, bold: true },
        },
        'value-3': {
          id: 'value-3',
          type: PageElementTypeEnum.Text,
          transform: { left: 966, top: 522, width: 120, height: 44, rotation: 0 },
          text: '54%',
          textStyle: { color: '#0F172A', fontSize: 28, bold: true },
        },
      },
    },
    roadmap: {
      id: 'roadmap',
      pageType: PageTypeEnum.Slide,
      name: 'Roadmap',
      background: {
        type: SlideBackgroundTypeEnum.Solid,
        color: '#FFFDF8',
      },
      elementOrder: ['title', 'line', 'phase-1', 'phase-2', 'phase-3', 'phase-4'],
      elements: {
        title: {
          id: 'title',
          type: PageElementTypeEnum.Text,
          transform: { left: 86, top: 76, width: 800, height: 64, rotation: 0 },
          text: 'Four moments to launch',
          textStyle: { color: '#1E293B', fontSize: 38, bold: true },
        },
        line: {
          id: 'line',
          type: PageElementTypeEnum.Shape,
          transform: { left: 142, top: 324, width: 900, height: 8, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#CBD5E1' },
            stroke: { color: '#CBD5E1', width: 0 },
          },
        },
        'phase-1': {
          id: 'phase-1',
          type: PageElementTypeEnum.Shape,
          transform: { left: 100, top: 230, width: 210, height: 188, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#E0F2FE' },
            stroke: { color: '#7DD3FC', width: 1 },
            shapeText: {
              isHorizontal: true,
              isRichText: false,
              text: '01\nALIGN\nAug 4–8',
              fontSize: 20,
              color: '#075985',
              bold: true,
            },
          },
        },
        'phase-2': {
          id: 'phase-2',
          type: PageElementTypeEnum.Shape,
          transform: { left: 364, top: 230, width: 210, height: 188, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#DCFCE7' },
            stroke: { color: '#86EFAC', width: 1 },
            shapeText: {
              isHorizontal: true,
              isRichText: false,
              text: '02\nBUILD\nAug 11–22',
              fontSize: 20,
              color: '#166534',
              bold: true,
            },
          },
        },
        'phase-3': {
          id: 'phase-3',
          type: PageElementTypeEnum.Shape,
          transform: { left: 628, top: 230, width: 210, height: 188, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#FEF3C7' },
            stroke: { color: '#FCD34D', width: 1 },
            shapeText: {
              isHorizontal: true,
              isRichText: false,
              text: '03\nVALIDATE\nAug 25–29',
              fontSize: 20,
              color: '#92400E',
              bold: true,
            },
          },
        },
        'phase-4': {
          id: 'phase-4',
          type: PageElementTypeEnum.Shape,
          transform: { left: 892, top: 230, width: 210, height: 188, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#FCE7F3' },
            stroke: { color: '#F9A8D4', width: 1 },
            shapeText: {
              isHorizontal: true,
              isRichText: false,
              text: '04\nLAUNCH\nSep 2',
              fontSize: 20,
              color: '#9D174D',
              bold: true,
            },
          },
        },
      },
    },
    close: {
      id: 'close',
      pageType: PageTypeEnum.Slide,
      name: 'Close',
      background: {
        type: SlideBackgroundTypeEnum.Solid,
        color: '#0F172A',
      },
      elementOrder: ['mark', 'title', 'subtitle'],
      elements: {
        mark: {
          id: 'mark',
          type: PageElementTypeEnum.Shape,
          transform: { left: 500, top: 136, width: 200, height: 16, rotation: 0 },
          shapeData: {
            shapeType: ShapeTypeEnum.RoundRect,
            fill: { color: '#38BDF8' },
            stroke: { color: '#38BDF8', width: 0 },
          },
        },
        title: {
          id: 'title',
          type: PageElementTypeEnum.Text,
          transform: { left: 180, top: 234, width: 840, height: 108, rotation: 0 },
          text: 'Ready when the team is.',
          textStyle: { color: '#F8FAFC', fontSize: 52, bold: true },
        },
        subtitle: {
          id: 'subtitle',
          type: PageElementTypeEnum.Text,
          transform: { left: 300, top: 374, width: 600, height: 72, rotation: 0 },
          text: 'Plan, present, publish — without leaving Univer.',
          textStyle: { color: '#94A3B8', fontSize: 23 },
        },
      },
    },
  },
}
