import type { ISlideData, ISlideShapeElement } from '@univerjs-pro/slides'
import {
  ShapeFillEnum,
  ShapeLineTypeEnum,
  ShapeTextAutoFitType,
  ShapeTextWrapType,
  ShapeTypeEnum,
} from '@univerjs-pro/engine-shape'
import { PageElementTypeEnum, PageTypeEnum, SlideBackgroundTypeEnum } from '@univerjs-pro/slides'
import { LocaleType } from '@univerjs/core'

const SLIDE_WIDTH = 840
const SLIDE_HEIGHT = 472.5
const CARD_PADDING = { left: 18, top: 14, right: 18, bottom: 14 }

interface ITextShapeOptions {
  bold?: boolean
  color: string
  fontSize: number
  height: number
  id: string
  left: number
  text: string
  top: number
  width: number
}

interface ICardShapeOptions extends ITextShapeOptions {
  fill: string
  shapeType?: ShapeTypeEnum
  stroke: string
}

function createTextShape(options: ITextShapeOptions): ISlideShapeElement {
  return {
    id: options.id,
    type: PageElementTypeEnum.Shape,
    transform: {
      left: options.left,
      top: options.top,
      width: options.width,
      height: options.height,
      rotation: 0,
    },
    shapeData: {
      shapeType: ShapeTypeEnum.Rect,
      isTextBox: true,
      fill: { fillType: ShapeFillEnum.NoFill },
      stroke: { lineStrokeType: ShapeLineTypeEnum.NoLine },
      textRectPadding: { left: 0, top: 0, right: 0, bottom: 0 },
      shapeText: {
        isHorizontal: true,
        isRichText: false,
        text: options.text,
        color: options.color,
        fontFamily: 'Arial',
        fontSize: options.fontSize,
        bold: options.bold,
        autoFitType: ShapeTextAutoFitType.NormAutoFit,
        textWrap: ShapeTextWrapType.Square,
      },
    },
  }
}

function createCenteredTextShape(options: ITextShapeOptions): ISlideShapeElement {
  return {
    id: options.id,
    type: PageElementTypeEnum.Shape,
    transform: {
      left: options.left,
      top: options.top,
      width: options.width,
      height: options.height,
      rotation: 0,
    },
    shapeData: {
      shapeType: ShapeTypeEnum.Rect,
      fill: { fillType: ShapeFillEnum.NoFill },
      stroke: { lineStrokeType: ShapeLineTypeEnum.NoLine },
      textRectPadding: { left: 0, top: 0, right: 0, bottom: 0 },
      shapeText: {
        isHorizontal: true,
        isRichText: false,
        text: options.text,
        color: options.color,
        fontFamily: 'Arial',
        fontSize: options.fontSize,
        bold: options.bold,
        autoFitType: ShapeTextAutoFitType.NoAutoFit,
        textWrap: ShapeTextWrapType.Square,
      },
    },
  }
}

function createCardShape(options: ICardShapeOptions): ISlideShapeElement {
  return {
    id: options.id,
    type: PageElementTypeEnum.Shape,
    transform: {
      left: options.left,
      top: options.top,
      width: options.width,
      height: options.height,
      rotation: 0,
    },
    shapeData: {
      shapeType: options.shapeType ?? ShapeTypeEnum.RoundRect,
      fill: { fillType: ShapeFillEnum.SolidFill, color: options.fill },
      stroke: { lineStrokeType: ShapeLineTypeEnum.SolidLine, color: options.stroke, width: 1 },
      textRectPadding: CARD_PADDING,
      shapeText: {
        isHorizontal: true,
        isRichText: false,
        text: options.text,
        color: options.color,
        fontFamily: 'Arial',
        fontSize: options.fontSize,
        bold: options.bold,
        autoFitType: ShapeTextAutoFitType.NormAutoFit,
        textWrap: ShapeTextWrapType.Square,
      },
    },
  }
}

function createDecorativeShape(
  id: string,
  shapeType: ShapeTypeEnum,
  left: number,
  top: number,
  width: number,
  height: number,
  fill: string,
  stroke = fill,
): ISlideShapeElement {
  return {
    id,
    type: PageElementTypeEnum.Shape,
    transform: { left, top, width, height, rotation: 0 },
    shapeData: {
      shapeType,
      fill: { fillType: ShapeFillEnum.SolidFill, color: fill },
      stroke: { lineStrokeType: ShapeLineTypeEnum.SolidLine, color: stroke, width: 0 },
    },
  }
}

export const homeSlideData: ISlideData = {
  id: 'northstar-launch-story',
  name: 'Northstar Global Launch',
  appVersion: '1.0.0-beta.2',
  rev: 2,
  locale: LocaleType.EN_US,
  defaultPageSize: { width: SLIDE_WIDTH, height: SLIDE_HEIGHT },
  slideOrder: ['cover', 'scorecard', 'readiness', 'system', 'decision'],
  activeSlideId: 'cover',
  zoomRatio: 1,
  slides: {
    cover: {
      id: 'cover',
      pageType: PageTypeEnum.Slide,
      name: 'Executive brief',
      background: { type: SlideBackgroundTypeEnum.Solid, color: '#0B1F33' },
      elementOrder: [
        'accent-orbit',
        'accent-core',
        'accent-line',
        'eyebrow',
        'title',
        'subtitle',
        'readiness-card',
        'date-card',
        'footer',
      ],
      elements: {
        'accent-orbit': createDecorativeShape('accent-orbit', ShapeTypeEnum.Ellipse, 610, -86, 320, 320, '#143A52'),
        'accent-core': createDecorativeShape('accent-core', ShapeTypeEnum.Ellipse, 688, -8, 164, 164, '#1F9D8B'),
        'accent-line': createDecorativeShape('accent-line', ShapeTypeEnum.Rect, 58, 78, 54, 5, '#F59E0B'),
        eyebrow: createTextShape({
          id: 'eyebrow',
          left: 58,
          top: 46,
          width: 460,
          height: 24,
          text: 'NORTHSTAR  /  GLOBAL LAUNCH 2026',
          color: '#73D6C9',
          fontSize: 13,
          bold: true,
        }),
        title: createTextShape({
          id: 'title',
          left: 58,
          top: 108,
          width: 565,
          height: 122,
          text: 'One launch.\nEvery team aligned.',
          color: '#F8FAFC',
          fontSize: 43,
          bold: true,
        }),
        subtitle: createTextShape({
          id: 'subtitle',
          left: 60,
          top: 250,
          width: 520,
          height: 62,
          text: 'Executive readiness brief  ·  22 August 2026',
          color: '#B8C9D9',
          fontSize: 17,
        }),
        'readiness-card': createCardShape({
          id: 'readiness-card',
          left: 600,
          top: 252,
          width: 178,
          height: 112,
          text: '86%\nREADY',
          fill: '#F8FAFC',
          stroke: '#D9E2EC',
          color: '#102A43',
          fontSize: 25,
          bold: true,
        }),
        'date-card': createCardShape({
          id: 'date-card',
          left: 60,
          top: 350,
          width: 262,
          height: 52,
          text: 'GO-LIVE  ·  22 SEP 2026',
          fill: '#163C55',
          stroke: '#2B5870',
          color: '#F8FAFC',
          fontSize: 15,
          bold: true,
        }),
        footer: createTextShape({
          id: 'footer',
          left: 60,
          top: 430,
          width: 640,
          height: 20,
          text: 'PRODUCT OPERATIONS  ·  CONFIDENTIAL',
          color: '#7693A8',
          fontSize: 11,
          bold: true,
        }),
      },
    },
    scorecard: {
      id: 'scorecard',
      pageType: PageTypeEnum.Slide,
      name: 'Readiness scorecard',
      background: { type: SlideBackgroundTypeEnum.Solid, color: '#F7F4ED' },
      elementOrder: [
        'eyebrow',
        'title',
        'subtitle',
        'card-1',
        'card-1-accent',
        'card-1-metric',
        'card-1-label',
        'card-1-detail',
        'card-2',
        'card-2-accent',
        'card-2-metric',
        'card-2-label',
        'card-2-detail',
        'card-3',
        'card-3-accent',
        'card-3-metric',
        'card-3-label',
        'card-3-detail',
        'card-4',
        'card-4-accent',
        'card-4-metric',
        'card-4-label',
        'card-4-detail',
        'decision-strip',
        'decision-label',
        'decision-text',
      ],
      elements: {
        eyebrow: createTextShape({
          id: 'eyebrow',
          left: 54,
          top: 27,
          width: 210,
          height: 18,
          text: '01  /  EXECUTIVE SIGNALS',
          color: '#0F766E',
          fontSize: 10,
          bold: true,
        }),
        title: createTextShape({
          id: 'title',
          left: 54,
          top: 55,
          width: 650,
          height: 42,
          text: 'Readiness is up eight points',
          color: '#102A43',
          fontSize: 29,
          bold: true,
        }),
        subtitle: createTextShape({
          id: 'subtitle',
          left: 56,
          top: 101,
          width: 700,
          height: 24,
          text: 'Four signals determine the go / no-go decision',
          color: '#627D98',
          fontSize: 14,
        }),
        'card-1': createCardShape({
          id: 'card-1',
          left: 54,
          top: 154,
          width: 170,
          height: 174,
          text: '',
          fill: '#FFFFFF',
          stroke: '#C6EDE7',
          color: '#115E59',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'card-1-accent': createDecorativeShape('card-1-accent', ShapeTypeEnum.Rect, 54, 154, 170, 5, '#1F9D8B'),
        'card-1-metric': createCenteredTextShape({
          id: 'card-1-metric',
          left: 54,
          top: 181,
          width: 170,
          height: 40,
          text: '86%',
          color: '#115E59',
          fontSize: 27,
          bold: true,
        }),
        'card-1-label': createCenteredTextShape({
          id: 'card-1-label',
          left: 54,
          top: 231,
          width: 170,
          height: 22,
          text: 'READY',
          color: '#115E59',
          fontSize: 12,
          bold: true,
        }),
        'card-1-detail': createCenteredTextShape({
          id: 'card-1-detail',
          left: 54,
          top: 271,
          width: 170,
          height: 22,
          text: '+8 points',
          color: '#5C7F7A',
          fontSize: 11,
          bold: true,
        }),
        'card-2': createCardShape({
          id: 'card-2',
          left: 242,
          top: 154,
          width: 170,
          height: 174,
          text: '',
          fill: '#FFFFFF',
          stroke: '#D6E4FF',
          color: '#1E3A8A',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'card-2-accent': createDecorativeShape('card-2-accent', ShapeTypeEnum.Rect, 242, 154, 170, 5, '#3B82F6'),
        'card-2-metric': createCenteredTextShape({
          id: 'card-2-metric',
          left: 242,
          top: 181,
          width: 170,
          height: 40,
          text: '2 / 9',
          color: '#1E3A8A',
          fontSize: 27,
          bold: true,
        }),
        'card-2-label': createCenteredTextShape({
          id: 'card-2-label',
          left: 242,
          top: 231,
          width: 170,
          height: 22,
          text: 'DONE',
          color: '#1E3A8A',
          fontSize: 12,
          bold: true,
        }),
        'card-2-detail': createCenteredTextShape({
          id: 'card-2-detail',
          left: 242,
          top: 271,
          width: 170,
          height: 22,
          text: '+1 this week',
          color: '#6479A8',
          fontSize: 11,
          bold: true,
        }),
        'card-3': createCardShape({
          id: 'card-3',
          left: 430,
          top: 154,
          width: 170,
          height: 174,
          text: '',
          fill: '#FFFCF5',
          stroke: '#F7E2B0',
          color: '#9A3412',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'card-3-accent': createDecorativeShape('card-3-accent', ShapeTypeEnum.Rect, 430, 154, 170, 5, '#F59E0B'),
        'card-3-metric': createCenteredTextShape({
          id: 'card-3-metric',
          left: 430,
          top: 181,
          width: 170,
          height: 40,
          text: '$875K',
          color: '#9A3412',
          fontSize: 27,
          bold: true,
        }),
        'card-3-label': createCenteredTextShape({
          id: 'card-3-label',
          left: 430,
          top: 231,
          width: 170,
          height: 22,
          text: 'FORECAST',
          color: '#9A3412',
          fontSize: 12,
          bold: true,
        }),
        'card-3-detail': createCenteredTextShape({
          id: 'card-3-detail',
          left: 430,
          top: 271,
          width: 170,
          height: 22,
          text: '99% of cap',
          color: '#A46A4D',
          fontSize: 11,
          bold: true,
        }),
        'card-4': createCardShape({
          id: 'card-4',
          left: 618,
          top: 154,
          width: 170,
          height: 174,
          text: '',
          fill: '#FFF8F7',
          stroke: '#F3D1D1',
          color: '#991B1B',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'card-4-accent': createDecorativeShape('card-4-accent', ShapeTypeEnum.Rect, 618, 154, 170, 5, '#E25555'),
        'card-4-metric': createCenteredTextShape({
          id: 'card-4-metric',
          left: 618,
          top: 181,
          width: 170,
          height: 40,
          text: '2',
          color: '#991B1B',
          fontSize: 27,
          bold: true,
        }),
        'card-4-label': createCenteredTextShape({
          id: 'card-4-label',
          left: 618,
          top: 231,
          width: 170,
          height: 22,
          text: 'HIGH RISK',
          color: '#991B1B',
          fontSize: 12,
          bold: true,
        }),
        'card-4-detail': createCenteredTextShape({
          id: 'card-4-detail',
          left: 618,
          top: 271,
          width: 170,
          height: 22,
          text: '1 decision',
          color: '#A46363',
          fontSize: 11,
          bold: true,
        }),
        'decision-strip': createCardShape({
          id: 'decision-strip',
          left: 54,
          top: 358,
          width: 734,
          height: 58,
          text: '',
          fill: '#102A43',
          stroke: '#102A43',
          color: '#FFFFFF',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'decision-label': createCenteredTextShape({
          id: 'decision-label',
          left: 68,
          top: 375,
          width: 108,
          height: 20,
          text: 'DECISION',
          color: '#73D6C9',
          fontSize: 11,
          bold: true,
        }),
        'decision-text': createCenteredTextShape({
          id: 'decision-text',
          left: 182,
          top: 370,
          width: 585,
          height: 30,
          text: 'Launch approved with a $15K billing reserve',
          color: '#FFFFFF',
          fontSize: 14,
          bold: true,
        }),
      },
    },
    readiness: {
      id: 'readiness',
      pageType: PageTypeEnum.Slide,
      name: 'Readiness by workstream',
      background: { type: SlideBackgroundTypeEnum.Solid, color: '#FFFFFF' },
      elementOrder: [
        'eyebrow',
        'title',
        'subtitle',
        'label-1',
        'rail-1',
        'bar-1',
        'value-1',
        'label-2',
        'rail-2',
        'bar-2',
        'value-2',
        'label-3',
        'rail-3',
        'bar-3',
        'value-3',
        'label-4',
        'rail-4',
        'bar-4',
        'value-4',
        'risk-note',
        'risk-accent',
        'risk-label',
        'risk-text',
      ],
      elements: {
        eyebrow: createTextShape({
          id: 'eyebrow',
          left: 54,
          top: 25,
          width: 185,
          height: 18,
          text: '02  /  READINESS',
          color: '#0F766E',
          fontSize: 10,
          bold: true,
        }),
        title: createTextShape({
          id: 'title',
          left: 54,
          top: 53,
          width: 670,
          height: 42,
          text: 'Where the launch is moving',
          color: '#102A43',
          fontSize: 29,
          bold: true,
        }),
        subtitle: createTextShape({
          id: 'subtitle',
          left: 56,
          top: 100,
          width: 650,
          height: 23,
          text: 'Completion by critical workstream',
          color: '#627D98',
          fontSize: 14,
        }),
        'label-1': createTextShape({
          id: 'label-1',
          left: 56,
          top: 146,
          width: 230,
          height: 24,
          text: 'Release candidate',
          color: '#334E68',
          fontSize: 15,
          bold: true,
        }),
        'rail-1': createDecorativeShape('rail-1', ShapeTypeEnum.RoundRect, 294, 151, 404, 17, '#E6EEF5'),
        'bar-1': createDecorativeShape('bar-1', ShapeTypeEnum.RoundRect, 294, 151, 404, 17, '#1F9D8B'),
        'value-1': createTextShape({
          id: 'value-1',
          left: 718,
          top: 143,
          width: 68,
          height: 28,
          text: '100%',
          color: '#0F766E',
          fontSize: 17,
          bold: true,
        }),
        'label-2': createTextShape({
          id: 'label-2',
          left: 56,
          top: 205,
          width: 230,
          height: 24,
          text: 'Enterprise onboarding',
          color: '#334E68',
          fontSize: 15,
          bold: true,
        }),
        'rail-2': createDecorativeShape('rail-2', ShapeTypeEnum.RoundRect, 294, 210, 404, 17, '#E6EEF5'),
        'bar-2': createDecorativeShape('bar-2', ShapeTypeEnum.RoundRect, 294, 210, 356, 17, '#3B82F6'),
        'value-2': createTextShape({
          id: 'value-2',
          left: 718,
          top: 202,
          width: 68,
          height: 28,
          text: '88%',
          color: '#1D4ED8',
          fontSize: 17,
          bold: true,
        }),
        'label-3': createTextShape({
          id: 'label-3',
          left: 56,
          top: 264,
          width: 230,
          height: 24,
          text: 'Partner certification',
          color: '#334E68',
          fontSize: 15,
          bold: true,
        }),
        'rail-3': createDecorativeShape('rail-3', ShapeTypeEnum.RoundRect, 294, 269, 404, 17, '#E6EEF5'),
        'bar-3': createDecorativeShape('bar-3', ShapeTypeEnum.RoundRect, 294, 269, 307, 17, '#F59E0B'),
        'value-3': createTextShape({
          id: 'value-3',
          left: 718,
          top: 261,
          width: 68,
          height: 28,
          text: '76%',
          color: '#B45309',
          fontSize: 17,
          bold: true,
        }),
        'label-4': createTextShape({
          id: 'label-4',
          left: 56,
          top: 323,
          width: 230,
          height: 24,
          text: 'Billing migration',
          color: '#334E68',
          fontSize: 15,
          bold: true,
        }),
        'rail-4': createDecorativeShape('rail-4', ShapeTypeEnum.RoundRect, 294, 328, 404, 17, '#E6EEF5'),
        'bar-4': createDecorativeShape('bar-4', ShapeTypeEnum.RoundRect, 294, 328, 210, 17, '#E25555'),
        'value-4': createTextShape({
          id: 'value-4',
          left: 718,
          top: 320,
          width: 68,
          height: 28,
          text: '52%',
          color: '#B91C1C',
          fontSize: 17,
          bold: true,
        }),
        'risk-note': createCardShape({
          id: 'risk-note',
          left: 54,
          top: 385,
          width: 734,
          height: 48,
          text: '',
          fill: '#FEF2F2',
          stroke: '#FECACA',
          color: '#991B1B',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'risk-accent': createDecorativeShape('risk-accent', ShapeTypeEnum.Rect, 54, 385, 6, 48, '#E25555'),
        'risk-label': createCenteredTextShape({
          id: 'risk-label',
          left: 70,
          top: 399,
          width: 74,
          height: 20,
          text: 'WATCH',
          color: '#991B1B',
          fontSize: 11,
          bold: true,
        }),
        'risk-text': createCenteredTextShape({
          id: 'risk-text',
          left: 146,
          top: 396,
          width: 620,
          height: 26,
          text: 'Billing scope is the only remaining launch-date risk',
          color: '#991B1B',
          fontSize: 13,
          bold: true,
        }),
      },
    },
    system: {
      id: 'system',
      pageType: PageTypeEnum.Slide,
      name: 'Operating system',
      background: { type: SlideBackgroundTypeEnum.Solid, color: '#F3F7F9' },
      elementOrder: [
        'eyebrow',
        'title',
        'subtitle',
        'step-1',
        'step-1-number',
        'step-1-title',
        'step-1-detail',
        'arrow-1',
        'step-2',
        'step-2-number',
        'step-2-title',
        'step-2-detail',
        'arrow-2',
        'step-3',
        'step-3-number',
        'step-3-title',
        'step-3-detail',
        'arrow-3',
        'step-4',
        'step-4-number',
        'step-4-title',
        'step-4-detail',
        'caption',
      ],
      elements: {
        eyebrow: createTextShape({
          id: 'eyebrow',
          left: 54,
          top: 25,
          width: 230,
          height: 18,
          text: '03  /  OPERATING SYSTEM',
          color: '#0F766E',
          fontSize: 10,
          bold: true,
        }),
        title: createTextShape({
          id: 'title',
          left: 54,
          top: 53,
          width: 660,
          height: 42,
          text: 'A connected operating system',
          color: '#102A43',
          fontSize: 29,
          bold: true,
        }),
        subtitle: createTextShape({
          id: 'subtitle',
          left: 56,
          top: 100,
          width: 700,
          height: 23,
          text: 'Each workspace moves one decision closer to launch',
          color: '#627D98',
          fontSize: 14,
        }),
        'step-1': createCardShape({
          id: 'step-1',
          left: 54,
          top: 170,
          width: 150,
          height: 156,
          text: '',
          fill: '#E6FFFA',
          stroke: '#99F6E4',
          color: '#115E59',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'step-1-number': createCenteredTextShape({
          id: 'step-1-number',
          left: 54,
          top: 187,
          width: 150,
          height: 22,
          text: '01',
          color: '#0F766E',
          fontSize: 13,
          bold: true,
        }),
        'step-1-title': createCenteredTextShape({
          id: 'step-1-title',
          left: 54,
          top: 218,
          width: 150,
          height: 34,
          text: 'PLAN',
          color: '#115E59',
          fontSize: 21,
          bold: true,
        }),
        'step-1-detail': createCenteredTextShape({
          id: 'step-1-detail',
          left: 54,
          top: 267,
          width: 150,
          height: 24,
          text: 'Signals + budget',
          color: '#397A73',
          fontSize: 11,
          bold: true,
        }),
        'arrow-1': createDecorativeShape('arrow-1', ShapeTypeEnum.RightArrow, 212, 226, 28, 40, '#9FB3C8'),
        'step-2': createCardShape({
          id: 'step-2',
          left: 248,
          top: 170,
          width: 150,
          height: 156,
          text: '',
          fill: '#EFF6FF',
          stroke: '#BFDBFE',
          color: '#1E3A8A',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'step-2-number': createCenteredTextShape({
          id: 'step-2-number',
          left: 248,
          top: 187,
          width: 150,
          height: 22,
          text: '02',
          color: '#3157A4',
          fontSize: 13,
          bold: true,
        }),
        'step-2-title': createCenteredTextShape({
          id: 'step-2-title',
          left: 248,
          top: 218,
          width: 150,
          height: 34,
          text: 'PROVE',
          color: '#1E3A8A',
          fontSize: 21,
          bold: true,
        }),
        'step-2-detail': createCenteredTextShape({
          id: 'step-2-detail',
          left: 248,
          top: 267,
          width: 150,
          height: 24,
          text: 'Brief + evidence',
          color: '#4B65A2',
          fontSize: 11,
          bold: true,
        }),
        'arrow-2': createDecorativeShape('arrow-2', ShapeTypeEnum.RightArrow, 406, 226, 28, 40, '#9FB3C8'),
        'step-3': createCardShape({
          id: 'step-3',
          left: 442,
          top: 170,
          width: 150,
          height: 156,
          text: '',
          fill: '#FFF7ED',
          stroke: '#FED7AA',
          color: '#9A3412',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'step-3-number': createCenteredTextShape({
          id: 'step-3-number',
          left: 442,
          top: 187,
          width: 150,
          height: 22,
          text: '03',
          color: '#B45309',
          fontSize: 13,
          bold: true,
        }),
        'step-3-title': createCenteredTextShape({
          id: 'step-3-title',
          left: 442,
          top: 218,
          width: 150,
          height: 34,
          text: 'ACTIVATE',
          color: '#9A3412',
          fontSize: 18,
          bold: true,
        }),
        'step-3-detail': createCenteredTextShape({
          id: 'step-3-detail',
          left: 442,
          top: 267,
          width: 150,
          height: 24,
          text: 'Owners + markets',
          color: '#B25A3D',
          fontSize: 11,
          bold: true,
        }),
        'arrow-3': createDecorativeShape('arrow-3', ShapeTypeEnum.RightArrow, 600, 226, 28, 40, '#9FB3C8'),
        'step-4': createCardShape({
          id: 'step-4',
          left: 636,
          top: 170,
          width: 150,
          height: 156,
          text: '',
          fill: '#102A43',
          stroke: '#102A43',
          color: '#FFFFFF',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'step-4-number': createCenteredTextShape({
          id: 'step-4-number',
          left: 636,
          top: 187,
          width: 150,
          height: 22,
          text: '04',
          color: '#B8C9D9',
          fontSize: 13,
          bold: true,
        }),
        'step-4-title': createCenteredTextShape({
          id: 'step-4-title',
          left: 636,
          top: 218,
          width: 150,
          height: 34,
          text: 'LAUNCH',
          color: '#FFFFFF',
          fontSize: 20,
          bold: true,
        }),
        'step-4-detail': createCenteredTextShape({
          id: 'step-4-detail',
          left: 636,
          top: 267,
          width: 150,
          height: 24,
          text: '22 September',
          color: '#B8C9D9',
          fontSize: 11,
          bold: true,
        }),
        caption: createTextShape({
          id: 'caption',
          left: 54,
          top: 370,
          width: 730,
          height: 48,
          text: 'Sheets → Docs → Slides → Bases → Boards → PDFs',
          color: '#486581',
          fontSize: 18,
          bold: true,
        }),
      },
    },
    decision: {
      id: 'decision',
      pageType: PageTypeEnum.Slide,
      name: 'Decision',
      background: { type: SlideBackgroundTypeEnum.Solid, color: '#0B1F33' },
      elementOrder: [
        'go-circle',
        'go-label',
        'eyebrow',
        'accent-line',
        'title',
        'subtitle',
        'action-1',
        'action-1-label',
        'action-1-text',
        'action-2',
        'action-2-label',
        'action-2-text',
        'footer',
      ],
      elements: {
        'go-circle': createDecorativeShape('go-circle', ShapeTypeEnum.Ellipse, 612, 74, 170, 170, '#1F9D8B'),
        'go-label': createTextShape({
          id: 'go-label',
          left: 647,
          top: 124,
          width: 100,
          height: 66,
          text: 'GO',
          color: '#FFFFFF',
          fontSize: 39,
          bold: true,
        }),
        eyebrow: createTextShape({
          id: 'eyebrow',
          left: 58,
          top: 52,
          width: 390,
          height: 24,
          text: 'RECOMMENDATION',
          color: '#73D6C9',
          fontSize: 13,
          bold: true,
        }),
        'accent-line': createDecorativeShape('accent-line', ShapeTypeEnum.Rect, 58, 88, 48, 4, '#F59E0B'),
        title: createTextShape({
          id: 'title',
          left: 58,
          top: 104,
          width: 500,
          height: 104,
          text: 'Proceed with\nthe global launch.',
          color: '#F8FAFC',
          fontSize: 39,
          bold: true,
        }),
        subtitle: createTextShape({
          id: 'subtitle',
          left: 60,
          top: 228,
          width: 500,
          height: 56,
          text: 'Contain the billing risk.\nKeep every owner in rhythm.',
          color: '#B8C9D9',
          fontSize: 16,
        }),
        'action-1': createCardShape({
          id: 'action-1',
          left: 58,
          top: 316,
          width: 338,
          height: 68,
          text: '',
          fill: '#163C55',
          stroke: '#2B5870',
          color: '#F8FAFC',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'action-1-label': createCenteredTextShape({
          id: 'action-1-label',
          left: 58,
          top: 326,
          width: 338,
          height: 16,
          text: 'FINANCE',
          color: '#73D6C9',
          fontSize: 10,
          bold: true,
        }),
        'action-1-text': createCenteredTextShape({
          id: 'action-1-text',
          left: 58,
          top: 347,
          width: 338,
          height: 24,
          text: 'Hold $15K contingency',
          color: '#F8FAFC',
          fontSize: 14,
          bold: true,
        }),
        'action-2': createCardShape({
          id: 'action-2',
          left: 412,
          top: 316,
          width: 370,
          height: 68,
          text: '',
          fill: '#163C55',
          stroke: '#2B5870',
          color: '#F8FAFC',
          fontSize: 1,
          shapeType: ShapeTypeEnum.Rect,
        }),
        'action-2-label': createCenteredTextShape({
          id: 'action-2-label',
          left: 412,
          top: 326,
          width: 370,
          height: 16,
          text: 'PRODUCT OPERATIONS',
          color: '#73D6C9',
          fontSize: 10,
          bold: true,
        }),
        'action-2-text': createCenteredTextShape({
          id: 'action-2-text',
          left: 412,
          top: 347,
          width: 370,
          height: 24,
          text: 'Run daily risk review',
          color: '#F8FAFC',
          fontSize: 14,
          bold: true,
        }),
        footer: createTextShape({
          id: 'footer',
          left: 60,
          top: 430,
          width: 640,
          height: 20,
          text: 'NEXT CHECKPOINT  ·  TUESDAY 09:30',
          color: '#7693A8',
          fontSize: 11,
          bold: true,
        }),
      },
    },
  },
}
