import pkg from '@/package.json'

export const dependencies = {
  rxjs: 'latest',
  react: 'latest',
  'react-dom': 'latest',
  '@univerjs/core': pkg.version,
  '@univerjs/design': pkg.version,
  '@univerjs/engine-formula': pkg.version,
  '@univerjs/engine-numfmt': pkg.version,
  '@univerjs/engine-render': pkg.version,
  '@univerjs/rpc': pkg.version,
  '@univerjs/sheets': pkg.version,
  '@univerjs/ui': pkg.version,
  '@univerjs/docs': pkg.version,
  '@univerjs/docs-ui': pkg.version,
  '@univerjs/sheets-ui': pkg.version,
  '@univerjs/find-replace': pkg.version,
  '@univerjs/sheets-zen-editor': pkg.version,
  '@univerjs/sheets-find-replace': pkg.version,
  '@univerjs/sheets-conditional-formatting': pkg.version,
  '@univerjs/sheets-conditional-formatting-ui': pkg.version,
  '@univerjs/sheets-filter-ui': pkg.version,
  '@univerjs/thread-comment-ui': pkg.version,
  '@univerjs/drawing': pkg.version,
  '@univerjs/drawing-ui': pkg.version,
  '@univerjs/sheets-drawing-ui': pkg.version,
  '@univerjs/sheets-hyper-link-ui': pkg.version,
  '@univerjs/sheets-drawing': pkg.version,
  '@univerjs/sheets-sort-ui': pkg.version,
  '@univerjs/sheets-crosshair-highlight': pkg.version,
  '@univerjs/sheets-formula-ui': pkg.version,
  // TODO: Should be removed in the future
  '@univerjs/sheets-data-validation': pkg.version,
  '@univerjs/sheets-data-validation-ui': pkg.version,
  '@univerjs/watermark': pkg.version,
  '@univerjs/sheets-numfmt-ui': pkg.version,
  '@univerjs/sheets-thread-comment-ui': pkg.version,
  '@univerjs/sheets-table-ui': pkg.version,
  '@univerjs/sheets-note-ui': pkg.version,
}
