export const dependencies = {
  rxjs: 'latest',
  react: 'latest',
  'react-dom': 'latest',
  '@univerjs/core': '0.8.1',
  '@univerjs/design': '0.8.1',
  '@univerjs/engine-formula': '0.8.1',
  '@univerjs/engine-numfmt': '0.8.1',
  '@univerjs/engine-render': '0.8.1',
  '@univerjs/rpc': '0.8.1',
  '@univerjs/sheets': '0.8.1',
  '@univerjs/ui': '0.8.1',
  '@univerjs/docs': '0.8.1',
  '@univerjs/docs-ui': '0.8.1',
  '@univerjs/sheets-ui': '0.8.1',
  '@univerjs/sheets-formula': '0.8.1',
  '@univerjs/sheets-numfmt': '0.8.1',
  // '@univerjs/uniscript': 'latest',
  '@univerjs/network': '0.8.1',
  // '@univerjs/find-replace': 'latest',
  // '@univerjs/sheets-zen-editor': 'latest',
  // '@univerjs/sheets-find-replace': 'latest',
  // '@univerjs/slides': 'latest',
  // '@univerjs/slides-ui': 'latest',
  // '@univerjs/sheets-conditional-formatting': 'latest',
  // '@univerjs/data-validation': 'latest',
  // '@univerjs/sheets-conditional-formatting-ui': 'latest',
  // '@univerjs/sheets-data-validation': 'latest',
  // '@univerjs/sheets-filter': 'latest',
  // '@univerjs/sheets-filter-ui': 'latest',
  // '@univerjs/thread-comment': 'latest',
  // '@univerjs/thread-comment-ui': 'latest',
  // '@univerjs/sheets-thread-comment': 'latest',
  // '@univerjs/drawing': 'latest',
  // '@univerjs/sheets-hyper-link': 'latest',
  // '@univerjs/drawing-ui': 'latest',
  // '@univerjs/docs-drawing-ui': 'latest',
  // '@univerjs/sheets-drawing-ui': 'latest',
  // '@univerjs/sheets-hyper-link-ui': 'latest',
  // '@univerjs/docs-drawing': 'latest',
  // '@univerjs/sheets-drawing': 'latest',
  // '@univerjs/sheets-thread-comment-base': 'latest',
  // '@univerjs/sheets-sort': 'latest',
  // '@univerjs/sheets-sort-ui': 'latest',
  // '@univerjs/docs-hyper-link': 'latest',
  // '@univerjs/docs-hyper-link-ui': 'latest',
  // '@univerjs/docs-thread-comment-ui': 'latest',
  // '@univerjs/sheets-crosshair-highlight': 'latest',
  // '@univerjs/telemetry': 'latest',
  '@univerjs/sheets-formula-ui': '0.8.1',
  // '@univerjs/sheets-data-validation-ui': 'latest',
  // '@univerjs/watermark': 'latest',
  '@univerjs/sheets-numfmt-ui': '0.8.1',
  // '@univerjs/sheets-thread-comment-ui': 'latest',
  // '@univerjs/rpc-node': 'latest',
  // '@univerjs/preset-docs-collaboration': 'latest',
  // '@univerjs/preset-docs-core': 'latest',
  // '@univerjs/preset-docs-drawing': 'latest',
  // '@univerjs/preset-docs-hyper-link': 'latest',
  // '@univerjs/preset-docs-thread-comment': 'latest',
  // '@univerjs/preset-sheets-advanced': 'latest',
  // '@univerjs/preset-sheets-conditional-formatting': 'latest',
  // '@univerjs/preset-sheets-core': 'latest',
  // '@univerjs/preset-sheets-table': 'latest',
  // '@univerjs/preset-sheets-note': 'latest',
  // '@univerjs/themes': 'latest',
  // '@univerjs/preset-sheets-data-validation': 'latest',
  // '@univerjs/preset-sheets-drawing': 'latest',
  // '@univerjs/preset-sheets-filter': 'latest',
  // '@univerjs/preset-sheets-find-replace': 'latest',
  // '@univerjs/preset-sheets-hyper-link': 'latest',
  // '@univerjs/preset-sheets-node-core': 'latest',
  // '@univerjs/preset-sheets-sort': 'latest',
  // '@univerjs/preset-sheets-thread-comment': 'latest',
  // '@univerjs/preset-sheets-collaboration': 'latest',
  // '@univerjs/preset-docs-advanced': 'latest',
  // '@univerjs/presets': 'latest',
  // '@univerjs/action-recorder': 'latest',
  // '@univerjs/sheets-graphics': 'latest',
  // '@univerjs/docs-quick-insert-ui': 'latest',
  // '@univerjs/sheets-table': 'latest',
  // '@univerjs/sheets-table-ui': 'latest',
  // '@univerjs/sheets-note': 'latest',
  // '@univerjs/sheets-note-ui': 'latest',
  // '@univerjs-pro/print': 'latest',
  // '@univerjs-pro/collaboration': 'latest',
  // '@univerjs-pro/collaboration-client': 'latest',
  // '@univerjs-pro/sheets-data-connector': 'latest',
  // '@univerjs-pro/live-share': 'latest',
  // '@univerjs-pro/sheets-print': 'latest',
  // '@univerjs-pro/sheets-exchange-client': 'latest',
  // '@univerjs-pro/uniscript': 'latest',
  // '@univerjs-pro/edit-history-viewer': 'latest',
  // '@univerjs-pro/edit-history-loader': 'latest',
  // '@univerjs-pro/exchange-client': 'latest',
  // '@univerjs-pro/docs-exchange-client': 'latest',
  // '@univerjs-pro/pivot-engine': 'latest',
  // '@univerjs-pro/sheets-pivot': 'latest',
  // '@univerjs-pro/sheets-pivot-ui': 'latest',
  // '@univerjs-pro/thread-comment-datasource': 'latest',
  // '@univerjs-pro/engine-pivot': 'latest',
  // '@univerjs-pro/license': 'latest',
  // '@univerjs-pro/ai-auto-complete': 'latest',
  // '@univerjs-pro/drill-down-extraction': 'latest',
  // '@univerjs-pro/thread-comment-resource': 'latest',
  // '@univerjs-pro/sheets-chart': 'latest',
  // '@univerjs-pro/sheets-chart-ui': 'latest',
  // '@univerjs-pro/engine-formula': 'latest',
  // '@univerjs-pro/dev-changesets-replay': 'latest',
  // '@univerjs-pro/collaboration-client-ui': 'latest',
  // '@univerjs-pro/collaboration-client-node': 'latest',
  // '@univerjs-pro/telemetry': 'latest',
  // '@univerjs-pro/sheets-sparkline': 'latest',
  // '@univerjs-pro/sheets-sparkline-ui': 'latest',
  // '@univerjs-pro/engine-chart': 'latest',
}
