export const AGREEMENT = {
  title: 'Professional Services Agreement',
  parties: 'Atlas Systems, Inc. (“Provider”) and Northstar Retail Ltd. (“Customer”)',
  clauses: [
    ['1. Services', 'Provider will perform the implementation services described in Schedule A.'],
    ['2. Fees', 'Customer will pay fixed fees of $184,000 according to the milestone schedule.'],
    ['3. Term', 'The agreement begins 1 February 2027 and continues for twelve months.'],
    ['4. Confidentiality', 'Each party will protect non-public information using reasonable safeguards.'],
    ['5. Data protection', 'Processing is limited to documented instructions and the agreed security controls.'],
    ['6. Warranties', 'Each party warrants that it has authority to enter this agreement.'],
    ['7. Support', 'Severity-one incidents receive continuous response until mitigation.'],
    ['8. Change control', 'Scope changes require a written change order signed by both parties.'],
    ['9. Intellectual property', 'Each party retains its pre-existing intellectual property.'],
    ['10. Publicity', 'Neither party may use the other party’s marks without written consent.'],
    ['11. Insurance', 'Provider will maintain the coverage listed in Schedule B.'],
    ['12. Compliance', 'Both parties will comply with applicable anti-bribery and export laws.'],
    ['13. Termination', 'A material breach not cured within thirty days permits termination.'],
    ['14. General', 'Notices must be delivered to the addresses stated on the signature page.'],
  ],
  limitationBefore: ['15. Reserved', 'The parties will finalize the limitation language before signature.'],
  limitationAfter: [
    '15. Limitation of liability',
    'Aggregate liability is limited to fees paid in the twelve months before the claim, excluding confidentiality and data-protection breaches.',
  ],
  referenceBefore: 'Commercial approval: pending Clause 15.',
  referenceAfter: 'Commercial approval: Clause 15 accepted · cap equals twelve months of fees.',
} as const
