import type { IWorkbookData } from '@univerjs/presets'

export const WORKBOOK_DATA: Partial<IWorkbookData> = {
  id: 'swift-dispatch',
  name: 'Swift dispatch',
  sheetOrder: ['dispatch'],
  styles: {
    header: { bl: 1, bg: { rgb: '#DBEAFE' } },
    target: { bg: { rgb: '#FEF3C7' }, n: { pattern: '0' } },
    money: { n: { pattern: '$#,##0.00' } },
  },
  sheets: {
    dispatch: {
      id: 'dispatch',
      name: 'Dispatch',
      rowCount: 30,
      columnCount: 8,
      columnData: {
        0: { w: 135 },
        1: { w: 150 },
        2: { w: 125 },
        3: { w: 125 },
        4: { w: 125 },
        5: { w: 140 },
        6: { w: 160 },
        7: { w: 140 },
      },
      cellData: {
        0: { 0: { v: 'Swift dispatch · daily allocation' } },
        1: {
          0: { v: 'Van', s: 'header' },
          1: { v: 'Depot', s: 'header' },
          2: { v: 'Hours', s: 'header' },
          3: { v: 'Rate', s: 'header' },
          4: { v: 'Cost', s: 'header' },
          5: { v: 'Driver', s: 'header' },
          6: { v: 'Route', s: 'header' },
          7: { v: 'Status', s: 'header' },
        },
        2: {
          0: { v: 'SW-014' },
          1: { v: 'North quay' },
          2: { v: 6, s: 'target' },
          3: { v: 42, s: 'money' },
          4: { f: '=C3*D3', s: 'money' },
          5: { v: 'Ari' },
          6: { v: 'Coastal loop' },
          7: { v: 'Assigned' },
        },
        3: {
          0: { v: 'SW-027' },
          1: { v: 'Hill depot' },
          2: { v: 4.5 },
          3: { v: 38, s: 'money' },
          4: { f: '=C4*D4', s: 'money' },
          5: { v: 'Sam' },
          6: { v: 'Museum run' },
          7: { v: 'Standby' },
        },
        4: {
          0: { v: 'SW-031' },
          1: { v: 'West gate' },
          2: { v: 8 },
          3: { v: 45, s: 'money' },
          4: { f: '=C5*D5', s: 'money' },
          5: { v: 'Jules' },
          6: { v: 'Market express' },
          7: { v: 'Assigned' },
        },
      },
    },
  },
}
