import type { IWorkbookData } from '@univerjs/presets'

export const WORKBOOK_DATA: Partial<IWorkbookData> = {
  id: 'tide-museum',
  name: 'Tide Museum visitor timetable',
  sheetOrder: ['visits'],
  styles: {
    title: { bl: 1, fs: 18 },
    header: { bl: 1, bg: { rgb: '#DBEAFE' } },
    full: { bg: { rgb: '#FEF3C7' } },
    canceled: { cl: { rgb: '#64748B' } },
  },
  sheets: {
    visits: {
      id: 'visits',
      name: 'Visits',
      rowCount: 30,
      columnCount: 8,
      columnData: {
        0: { w: 100 },
        1: { w: 130 },
        2: { w: 240 },
        3: { w: 100 },
        4: { w: 100 },
        5: { w: 110 },
        6: { w: 140 },
      },
      cellData: {
        0: { 0: { v: 'Tide Museum · visitor timetable', s: 'title' } },
        1: { 0: { v: 'Fictional schedule · 2027-04-01 · frontend permission demonstration' } },
        2: {
          0: { v: 'Start', s: 'header' },
          1: { v: 'Room', s: 'header' },
          2: { v: 'Session', s: 'header' },
          3: { v: 'Capacity', s: 'header' },
          4: { v: 'Booked', s: 'header' },
          5: { v: 'Available', s: 'header' },
          6: { v: 'Status', s: 'header' },
        },
        3: {
          0: { v: '09:00' },
          1: { v: 'North gallery' },
          2: { v: 'A walk through the tides' },
          3: { v: 24 },
          4: { v: 18 },
          5: { f: '=D4-E4' },
          6: { v: 'Open' },
        },
        4: {
          0: { v: '11:00' },
          1: { v: 'Studio 2' },
          2: { v: 'Build a coastal model' },
          3: { v: 12 },
          4: { v: 12, s: 'full' },
          5: { f: '=D5-E5' },
          6: { v: 'Full', s: 'full' },
        },
        5: {
          0: { v: '13:30' },
          1: { v: 'Atrium' },
          2: { v: 'Meet the field researchers' },
          3: { v: 30 },
          4: { v: 0 },
          5: { f: '=D6-E6' },
          6: { v: 'Walk-in' },
        },
        6: {
          0: { v: '16:00', s: 'canceled' },
          1: { v: 'South dock' },
          2: { v: 'Harbor sketching' },
          3: { v: 16 },
          4: { v: 0 },
          5: { f: '=D7-E7' },
          6: { v: 'Canceled', s: 'canceled' },
        },
      },
    },
  },
}
